# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='comfirmed',
            new_name='confirmed',
        ),
    ]
