# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20160429_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
